base_url = "https://valium007.github.io"
title = "Valium"
description = "Blog"
theme = "archie-zola"

[markdown]
# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = "one-dark-pro"

# 2. If you want separate light/dark themes, use light_theme and dark_theme instead (remove `theme` above if so).

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes (only needed for CUSTOM themes, not built-ins)
# Get themes from https://textmate-grammars-themes.netlify.app/
extra_themes = []


[extra]
copyright = "Valium"
mode = "dark"  # auto | dark | toggle
subtitle = "Your tagline here"

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 1 },
    { name = "Posts", url = "/posts", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
]

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/valium007"
